//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Automation.Languages.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kişi aktif..
        /// </summary>
        public static string activePeople {
            get {
                return ResourceManager.GetString("activePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Ekle.
        /// </summary>
        public static string adminCompanyAdd {
            get {
                return ResourceManager.GetString("adminCompanyAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görüntülemek istediğiniz şirketi seçiniz..
        /// </summary>
        public static string adminCompanyChooser {
            get {
                return ResourceManager.GetString("adminCompanyChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Seçim Ekranı.
        /// </summary>
        public static string adminCompanyChooserTitle {
            get {
                return ResourceManager.GetString("adminCompanyChooserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket ismi başarıyla kaydedildi! Kaydedilen şirkete ait şifre: {0}{1}.
        /// </summary>
        public static string adminCompanySave {
            get {
                return ResourceManager.GetString("adminCompanySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girilen şirkete ait bilgi zaten kayıtlıdır..
        /// </summary>
        public static string adminCompanySaveAlreadyExists {
            get {
                return ResourceManager.GetString("adminCompanySaveAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici Onay Şifresi.
        /// </summary>
        public static string adminConfirmation {
            get {
                return ResourceManager.GetString("adminConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici onay şifreniz geçersizdir.
        /// </summary>
        public static string adminConfirmationNotValid {
            get {
                return ResourceManager.GetString("adminConfirmationNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silmek istediğinize emin misiniz?.
        /// </summary>
        public static string areYouSureToDelete {
            get {
                return ResourceManager.GetString("areYouSureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış yapmak istediğinize emin misiniz?.
        /// </summary>
        public static string areYouSureToExit {
            get {
                return ResourceManager.GetString("areYouSureToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail onay şifresini tekrardan göndermek istediğinize emin misiniz?.
        /// </summary>
        public static string areYouSureToSendAgain {
            get {
                return ResourceManager.GetString("areYouSureToSendAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili Kişi.
        /// </summary>
        public static string authorized {
            get {
                return ResourceManager.GetString("authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alanlar boş bırakılamaz.
        /// </summary>
        public static string blanksCannotBeEmpty {
            get {
                return ResourceManager.GetString("blanksCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih bilgilerini kontrol ediniz..
        /// </summary>
        public static string checkDate {
            get {
                return ResourceManager.GetString("checkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmalar.
        /// </summary>
        public static string companies {
            get {
                return ResourceManager.GetString("companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri.
        /// </summary>
        public static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Ekle.
        /// </summary>
        public static string companyAdd {
            get {
                return ResourceManager.GetString("companyAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçili Müşteriyi Sil.
        /// </summary>
        public static string companyDelete {
            get {
                return ResourceManager.GetString("companyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Grafiği.
        /// </summary>
        public static string companyGraphic {
            get {
                return ResourceManager.GetString("companyGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Bilgileri.
        /// </summary>
        public static string companyInformation {
            get {
                return ResourceManager.GetString("companyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri bilgisi silindi..
        /// </summary>
        public static string companyInformationDeleted {
            get {
                return ResourceManager.GetString("companyInformationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri bilgileri kaydedildi!.
        /// </summary>
        public static string companyInformationSaved {
            get {
                return ResourceManager.GetString("companyInformationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket İsmi.
        /// </summary>
        public static string companyName {
            get {
                return ResourceManager.GetString("companyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlı Müşteriler.
        /// </summary>
        public static string companyRegistered {
            get {
                return ResourceManager.GetString("companyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteriyi Kaydet.
        /// </summary>
        public static string companySave {
            get {
                return ResourceManager.GetString("companySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri İş Aktiviteleri.
        /// </summary>
        public static string companyWorkActivities {
            get {
                return ResourceManager.GetString("companyWorkActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kıyasla.
        /// </summary>
        public static string compare {
            get {
                return ResourceManager.GetString("compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onayla.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay.
        /// </summary>
        public static string confirmation {
            get {
                return ResourceManager.GetString("confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre boş bırakılamaz.
        /// </summary>
        public static string confirmationIsEmpty {
            get {
                return ResourceManager.GetString("confirmationIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay şifreniz yanlıştır..
        /// </summary>
        public static string confirmationNumberInvalid {
            get {
                return ResourceManager.GetString("confirmationNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay Şifresi.
        /// </summary>
        public static string confirmationPassword {
            get {
                return ResourceManager.GetString("confirmationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici onay kodunuz ile kullanıcı kaydınız yapılacaktır..
        /// </summary>
        public static string confirmationText {
            get {
                return ResourceManager.GetString("confirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı.
        /// </summary>
        public static string connection {
            get {
                return ResourceManager.GetString("connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı Durumu.
        /// </summary>
        public static string connectionStatus {
            get {
                return ResourceManager.GetString("connectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm sorularınız için aşağıdaki iletişim adreslerini kullanarak bizimle iletişime geçebilirsiniz.
        /// </summary>
        public static string contactUsFromAdressess {
            get {
                return ResourceManager.GetString("contactUsFromAdressess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik.
        /// </summary>
        public static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girilen müşteriye ait bilgi kayıtlıdır..
        /// </summary>
        public static string customerAlreadyExists {
            get {
                return ResourceManager.GetString("customerAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri kayıt işlemi başarıyla gerçekleşti!.
        /// </summary>
        public static string customerSaved {
            get {
                return ResourceManager.GetString("customerSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Günlük Rapor.
        /// </summary>
        public static string dailyReport {
            get {
                return ResourceManager.GetString("dailyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihi.
        /// </summary>
        public static string dateBeginning {
            get {
                return ResourceManager.GetString("dateBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih aralıkları boş bırakılamaz..
        /// </summary>
        public static string dateCannotBeEmpty {
            get {
                return ResourceManager.GetString("dateCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç tarihi bitiş tarihinden önde olamaz..
        /// </summary>
        public static string dateCannotBePast {
            get {
                return ResourceManager.GetString("dateCannotBePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapor Tarihi.
        /// </summary>
        public static string dateChoose {
            get {
                return ResourceManager.GetString("dateChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturma Tarihi.
        /// </summary>
        public static string dateCreated {
            get {
                return ResourceManager.GetString("dateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Tarihi.
        /// </summary>
        public static string dateDue {
            get {
                return ResourceManager.GetString("dateDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Zaman.
        /// </summary>
        public static string dateDueTime {
            get {
                return ResourceManager.GetString("dateDueTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teslim Tarihi.
        /// </summary>
        public static string dateFinished {
            get {
                return ResourceManager.GetString("dateFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş tarihi geçmiş bir tarih olamaz..
        /// </summary>
        public static string dateIsPast {
            get {
                return ResourceManager.GetString("dateIsPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gün.
        /// </summary>
        public static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz.
        /// </summary>
        public static string device {
            get {
                return ResourceManager.GetString("device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz bilgisi kayıtlı durumdadır..
        /// </summary>
        public static string deviceAlreadyExist {
            get {
                return ResourceManager.GetString("deviceAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz Sayısı.
        /// </summary>
        public static string deviceAmount {
            get {
                return ResourceManager.GetString("deviceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz bilgisi silindi!.
        /// </summary>
        public static string deviceDeleted {
            get {
                return ResourceManager.GetString("deviceDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz bilgileri güncellendi!.
        /// </summary>
        public static string deviceInformationUpdated {
            get {
                return ResourceManager.GetString("deviceInformationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz Adı.
        /// </summary>
        public static string deviceName {
            get {
                return ResourceManager.GetString("deviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projesi Hazır Cihazlar.
        /// </summary>
        public static string deviceReady {
            get {
                return ResourceManager.GetString("deviceReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışan Cihazlar.
        /// </summary>
        public static string deviceRunning {
            get {
                return ResourceManager.GetString("deviceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihazlar.
        /// </summary>
        public static string devices {
            get {
                return ResourceManager.GetString("devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz Ekle.
        /// </summary>
        public static string devicesAdd {
            get {
                return ResourceManager.GetString("devicesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz kaydedildi!.
        /// </summary>
        public static string deviceSaved {
            get {
                return ResourceManager.GetString("deviceSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz Ayarları.
        /// </summary>
        public static string deviceSettings {
            get {
                return ResourceManager.GetString("deviceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz Bilgileri.
        /// </summary>
        public static string devicesInformation {
            get {
                return ResourceManager.GetString("devicesInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string explanation {
            get {
                return ResourceManager.GetString("explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string facebook {
            get {
                return ResourceManager.GetString("facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlemin gerçekleşebilmesi için alanların doldurulmuş olması gerekmektedir.
        /// </summary>
        public static string fillBlanks {
            get {
                return ResourceManager.GetString("fillBlanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boş bırakılamaz.
        /// </summary>
        public static string fillBlanksProduct {
            get {
                return ResourceManager.GetString("fillBlanksProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal Medya Hesaplarımızı Takip Edin.
        /// </summary>
        public static string followSocialMedia {
            get {
                return ResourceManager.GetString("followSocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Dön.
        /// </summary>
        public static string goBack {
            get {
                return ResourceManager.GetString("goBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string homePage {
            get {
                return ResourceManager.GetString("homePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı veya şifre yanlış.
        /// </summary>
        public static string incorrectIdOrPassword {
            get {
                return ResourceManager.GetString("incorrectIdOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string instagram {
            get {
                return ResourceManager.GetString("instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not.
        /// </summary>
        public static string lastExplanation {
            get {
                return ResourceManager.GetString("lastExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metraj.
        /// </summary>
        public static string length {
            get {
                return ResourceManager.GetString("length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Günlük Ortalama Metraj.
        /// </summary>
        public static string length_average_daily {
            get {
                return ResourceManager.GetString("length_average_daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aylık Metraj.
        /// </summary>
        public static string length_monthly {
            get {
                return ResourceManager.GetString("length_monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Metraj.
        /// </summary>
        public static string length_total {
            get {
                return ResourceManager.GetString("length_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metraj:.
        /// </summary>
        public static string lengthdot {
            get {
                return ResourceManager.GetString("lengthdot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn.
        /// </summary>
        public static string linkedin {
            get {
                return ResourceManager.GetString("linkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GÜNLÜK MAKİNE METRAJ UZUNLUĞU.
        /// </summary>
        public static string machineLength {
            get {
                return ResourceManager.GetString("machineLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANLIK MAKİNE HAT HIZI.
        /// </summary>
        public static string machineSpeed {
            get {
                return ResourceManager.GetString("machineSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makine Durumu:.
        /// </summary>
        public static string machineStatus {
            get {
                return ResourceManager.GetString("machineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılan İş.
        /// </summary>
        public static string machineWork {
            get {
                return ResourceManager.GetString("machineWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Adresi.
        /// </summary>
        public static string mailAddress {
            get {
                return ResourceManager.GetString("mailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Uzantısı.
        /// </summary>
        public static string mailChoose {
            get {
                return ResourceManager.GetString("mailChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçerli bir mail adresi giriniz.
        /// </summary>
        public static string mailEmpty {
            get {
                return ResourceManager.GetString("mailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Listesi.
        /// </summary>
        public static string mailList {
            get {
                return ResourceManager.GetString("mailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgileriniz girilen mail adresine gönderildi..
        /// </summary>
        public static string mailSent {
            get {
                return ResourceManager.GetString("mailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailiniz iletilmiştir. En uygun zamanda sizlere dönüş yapılacaktır..
        /// </summary>
        public static string mailSentSuccessful {
            get {
                return ResourceManager.GetString("mailSentSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listele.
        /// </summary>
        public static string makeList {
            get {
                return ResourceManager.GetString("makeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M E N Ü.
        /// </summary>
        public static string menuToggleButton {
            get {
                return ResourceManager.GetString("menuToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aylık Rapor.
        /// </summary>
        public static string monthlyReport {
            get {
                return ResourceManager.GetString("monthlyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim Soyisim.
        /// </summary>
        public static string nameSurname {
            get {
                return ResourceManager.GetString("nameSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnternet bağlantısı bulunamadı. İnternet bağlantınızı kontrol ettikten sonra tekrar deneyiniz.
        /// </summary>
        public static string noInternetConnection {
            get {
                return ResourceManager.GetString("noInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlı operatör bulunamadı. Önce operatör kaydı yapıp sonra tekrar deneyiniz..
        /// </summary>
        public static string noOperatorFound {
            get {
                return ResourceManager.GetString("noOperatorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirimler.
        /// </summary>
        public static string notifications {
            get {
                return ResourceManager.GetString("notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporlanacak kayıtlı veri bulunamadı..
        /// </summary>
        public static string nullDb {
            get {
                return ResourceManager.GetString("nullDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAMAM.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör Ekle.
        /// </summary>
        public static string operatorAdd {
            get {
                return ResourceManager.GetString("operatorAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör bilgisi kayıtlı durumdadır..
        /// </summary>
        public static string operatorAlreadyExist {
            get {
                return ResourceManager.GetString("operatorAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör Sayısı.
        /// </summary>
        public static string operatorAmount {
            get {
                return ResourceManager.GetString("operatorAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör bilgisi silindi!.
        /// </summary>
        public static string operatorDeleted {
            get {
                return ResourceManager.GetString("operatorDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör adı boş bırakılamaz. Kayıtlı operatörünüz yoksa operatörler sekmesinden kaydınızı gerçekleştriniz..
        /// </summary>
        public static string operatorEmpty {
            get {
                return ResourceManager.GetString("operatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör bilgisi güncellendi!.
        /// </summary>
        public static string operatorInformationUpdated {
            get {
                return ResourceManager.GetString("operatorInformationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatörleri Listele.
        /// </summary>
        public static string operatorList {
            get {
                return ResourceManager.GetString("operatorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör.
        /// </summary>
        public static string operators {
            get {
                return ResourceManager.GetString("operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opeartör kayıt işlemi başarıyla gerçekleşti!.
        /// </summary>
        public static string operatorSaved {
            get {
                return ResourceManager.GetString("operatorSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör Bilgileri.
        /// </summary>
        public static string operatorsInformation {
            get {
                return ResourceManager.GetString("operatorsInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör İsmi.
        /// </summary>
        public static string operatorsName {
            get {
                return ResourceManager.GetString("operatorsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatörler.
        /// </summary>
        public static string operatorss {
            get {
                return ResourceManager.GetString("operatorss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör Ayarları.
        /// </summary>
        public static string operatorsSettings {
            get {
                return ResourceManager.GetString("operatorsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör İş Aktiviteleri.
        /// </summary>
        public static string operatorsWorkActivities {
            get {
                return ResourceManager.GetString("operatorsWorkActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Tekrar.
        /// </summary>
        public static string passwordAgain {
            get {
                return ResourceManager.GetString("passwordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreler uyuşmamaktadır.
        /// </summary>
        public static string passwordDoesntMatch {
            get {
                return ResourceManager.GetString("passwordDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi Unuttum.
        /// </summary>
        public static string passwordForgotten {
            get {
                return ResourceManager.GetString("passwordForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz 5 ile 16  karakter aralığında olmalıdır.
        /// </summary>
        public static string passwordMinAndMax {
            get {
                return ResourceManager.GetString("passwordMinAndMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string phoneNumber {
            get {
                return ResourceManager.GetString("phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string portsChoose {
            get {
                return ResourceManager.GetString("portsChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün.
        /// </summary>
        public static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Ekle.
        /// </summary>
        public static string productAdd {
            get {
                return ResourceManager.GetString("productAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girilen ürüne ait bilgi kayıtlıdır..
        /// </summary>
        public static string productAlreadyExists {
            get {
                return ResourceManager.GetString("productAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünü Sil.
        /// </summary>
        public static string productDelete {
            get {
                return ResourceManager.GetString("productDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün bilgisi silindi..
        /// </summary>
        public static string productDeleted {
            get {
                return ResourceManager.GetString("productDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Bilgileri.
        /// </summary>
        public static string productInformation {
            get {
                return ResourceManager.GetString("productInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün İsmi.
        /// </summary>
        public static string productName {
            get {
                return ResourceManager.GetString("productName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlı Ürünler.
        /// </summary>
        public static string productRegistered {
            get {
                return ResourceManager.GetString("productRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        public static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün kayıt işlemi başarıyla gerçekleşti!.
        /// </summary>
        public static string productSaved {
            get {
                return ResourceManager.GetString("productSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje.
        /// </summary>
        public static string project {
            get {
                return ResourceManager.GetString("project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen projeyi iptal et.
        /// </summary>
        public static string projectAbort {
            get {
                return ResourceManager.GetString("projectAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Ekle.
        /// </summary>
        public static string projectAdd {
            get {
                return ResourceManager.GetString("projectAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Sayısı.
        /// </summary>
        public static string projectAmount {
            get {
                return ResourceManager.GetString("projectAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Seç.
        /// </summary>
        public static string projectChoose {
            get {
                return ResourceManager.GetString("projectChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni proje kaydı oluşturabilmeniz için gerekli alanları doldurun.
        /// </summary>
        public static string projectCreateNewRegister {
            get {
                return ResourceManager.GetString("projectCreateNewRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Günlük Proje Raporu.
        /// </summary>
        public static string projectDailyReport {
            get {
                return ResourceManager.GetString("projectDailyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçili Projeyi Sil.
        /// </summary>
        public static string projectDelete {
            get {
                return ResourceManager.GetString("projectDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje bilgisi silindi..
        /// </summary>
        public static string projectDeleted {
            get {
                return ResourceManager.GetString("projectDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Bilgileri.
        /// </summary>
        public static string projectInformation {
            get {
                return ResourceManager.GetString("projectInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Adı.
        /// </summary>
        public static string projectName {
            get {
                return ResourceManager.GetString("projectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeler.
        /// </summary>
        public static string projects {
            get {
                return ResourceManager.GetString("projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje başarıyla kaydedildi..
        /// </summary>
        public static string projectSaved {
            get {
                return ResourceManager.GetString("projectSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılan Projeler.
        /// </summary>
        public static string projectsDone {
            get {
                return ResourceManager.GetString("projectsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Günlük Proje.
        /// </summary>
        public static string projectsDoneDaily {
            get {
                return ResourceManager.GetString("projectsDoneDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aylık Projeler.
        /// </summary>
        public static string projectsDoneMonthly {
            get {
                return ResourceManager.GetString("projectsDoneMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haftalık Projeler.
        /// </summary>
        public static string projectsDoneWeekly {
            get {
                return ResourceManager.GetString("projectsDoneWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senelik Projeler.
        /// </summary>
        public static string projectsDoneYearly {
            get {
                return ResourceManager.GetString("projectsDoneYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Projeler.
        /// </summary>
        public static string projectsLast {
            get {
                return ResourceManager.GetString("projectsLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılacak Projeler.
        /// </summary>
        public static string projectsToDo {
            get {
                return ResourceManager.GetString("projectsToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışıyor Bilgi Adresi.
        /// </summary>
        public static string readingAdress1 {
            get {
                return ResourceManager.GetString("readingAdress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hız Adresi.
        /// </summary>
        public static string readingAdress2 {
            get {
                return ResourceManager.GetString("readingAdress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metraj Adresi.
        /// </summary>
        public static string readingAdress3 {
            get {
                return ResourceManager.GetString("readingAdress3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC Reset Adresi.
        /// </summary>
        public static string readingAdress4 {
            get {
                return ResourceManager.GetString("readingAdress4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yedek Adres.
        /// </summary>
        public static string readingAdress5 {
            get {
                return ResourceManager.GetString("readingAdress5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla.
        /// </summary>
        public static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporla.
        /// </summary>
        public static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Verileri Raporla.
        /// </summary>
        public static string reportAll {
            get {
                return ResourceManager.GetString("reportAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporlar.
        /// </summary>
        public static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturulan Rapor.
        /// </summary>
        public static string reportsCreated {
            get {
                return ResourceManager.GetString("reportsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafik Oluştur.
        /// </summary>
        public static string reportsCreateGraphic {
            get {
                return ResourceManager.GetString("reportsCreateGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapor Oluştur.
        /// </summary>
        public static string reportsCreateReport {
            get {
                return ResourceManager.GetString("reportsCreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçili tarihler arası raporlama yapılır.
        /// </summary>
        public static string reportSelectedDate {
            get {
                return ResourceManager.GetString("reportSelectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazırlanabilir Rapor.
        /// </summary>
        public static string reportsReady {
            get {
                return ResourceManager.GetString("reportsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni onay kodu talep edin!.
        /// </summary>
        public static string requireNewConfirmation {
            get {
                return ResourceManager.GetString("requireNewConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen Cihaz Sayısı: {0}/2.
        /// </summary>
        public static string selectedReport {
            get {
                return ResourceManager.GetString("selectedReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem yapabilmek için satır seçiniz..
        /// </summary>
        public static string selectRowToTakeAction {
            get {
                return ResourceManager.GetString("selectRowToTakeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göster.
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        public static string signOut {
            get {
                return ResourceManager.GetString("signOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        public static string signUp {
            get {
                return ResourceManager.GetString("signUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı kayıt işlemi başarıyla gerçekleşti!.
        /// </summary>
        public static string signUpSucceeded {
            get {
                return ResourceManager.GetString("signUpSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slave ID.
        /// </summary>
        public static string slaveID {
            get {
                return ResourceManager.GetString("slaveID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hız:.
        /// </summary>
        public static string speed {
            get {
                return ResourceManager.GetString("speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu.
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistem.
        /// </summary>
        public static string system {
            get {
                return ResourceManager.GetString("system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string twitter {
            get {
                return ResourceManager.GetString("twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity Otomasyon Sistemi.
        /// </summary>
        public static string unityAutomation {
            get {
                return ResourceManager.GetString("unityAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgiler güncellendi!.
        /// </summary>
        public static string updateSucceeded {
            get {
                return ResourceManager.GetString("updateSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı bulunamadı..
        /// </summary>
        public static string userNotFound {
            get {
                return ResourceManager.GetString("userNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Ayarları.
        /// </summary>
        public static string userSettings {
            get {
                return ResourceManager.GetString("userSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Sitesi.
        /// </summary>
        public static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoş Geldiniz!.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılan İş.
        /// </summary>
        public static string workingOn {
            get {
                return ResourceManager.GetString("workingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılan İş.
        /// </summary>
        public static string workOnLine {
            get {
                return ResourceManager.GetString("workOnLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Takibi.
        /// </summary>
        public static string workSetter {
            get {
                return ResourceManager.GetString("workSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yıllık Rapor.
        /// </summary>
        public static string yearlyReport {
            get {
                return ResourceManager.GetString("yearlyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz: {0}.
        /// </summary>
        public static string yourPassword {
            get {
                return ResourceManager.GetString("yourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string youtube {
            get {
                return ResourceManager.GetString("youtube", resourceCulture);
            }
        }
    }
}
